# Default values for titus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  name: backend

  replicaCount: 1

  image:
    repository: 711655675495.dkr.ecr.eu-west-1.amazonaws.com/titus-kitchen-sink-backend
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    host: api.noise-titus.nearform.com
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
        - api.noise-titus.nearform.com
        secretName: api.noise-titus.nearform.com-cert

  extraEnv:
    PGHOST: "noisedb.cbbm7etlo64v.eu-west-1.rds.amazonaws.com"
    PGPORT: "5432"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "titus"
    NF_COMMENTS_PGHOST: "titus-db"
    NF_COMMENTS_PGUSER: "titus"
    NF_COMMENTS_PASSWORD: "titus"
    NF_COMMENTS_DATABASE: "titus"
    REDIS_HOST: "noise-0001-001.svydcv.0001.euw1.cache.amazonaws.com"
    REDIS_PORT: "6379"
    REACT_APP_S3_UPLOADER_ENDPOINT: "http://titus-s3:4569"

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

db:
  name: db

  schedule: "15 14 * * *"
  annotations: {}
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: "1"
  successfulJobsHistoryLimit: "1"

  service:
    type: ClusterIP
    port: 5432

  image:
    tag: 711655675495.dkr.ecr.eu-west-1.amazonaws.com/titus-kitchen-sink-db
    tag: latest
    pullPolicy: IfNotPresent
  
  pod:
    annotations: {}

  priorityClassName: ""


  nodeSelector: {}

  tolerations: []

  affinity: {}

s3:
  name: fake-s3

  schedule: "15 14 * * *"
  annotations: {}
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: "1"
  successfulJobsHistoryLimit: "1"

  service:
    type: ClusterIP
    port: 80

  image:
    repository: mrister/fake-s3
    tag: latest
    pullPolicy: Always
  
  pod:
    annotations: {}

  priorityClassName: ""


  nodeSelector: {}

  tolerations: []

  affinity: {}