export const white = '#FFFFFF'
export const light = '#f7f7f7'
export const grayExtraLight = '#EEF1F5'
export const grayLight = '#CED4DE'
export const gray = '#7D899C'
export const grayDark = '#2D3747'
export const grayExtraDark = '#1D2330'
export const dark = '#13161F'

export const skyBlue = '#1FB6FF'
export const negative = '#EB4D4B'

export const blue = '#2165e5'
export const midnightBlue = '#194cac'
export const sand4 = '#6d6d68'
export const sand3 = '#908a8a'
export const sand2 = '#a8a4a3'
export const sand1 = '#f4f4f2'
export const supersplit = '#fd775e'
export const brunchPink = '#fd7a9e'
export const bubblegum = '#f9c3c0'
