version: '3.6'

services:

  titus-db:
    container_name: titus-db
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=titus
      - POSTGRES_PASSWORD=titus
      - POSTGRES_DB=titus
    ports:
      - 5432:5432
    volumes:
      - titus-pg-data:/var/lib/postgresql/data
      - ./packages/titus-backend/tools/initdb:/docker-entrypoint-initdb.d
      
  titus-hasura:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
    - "8080:8080"
    depends_on:
    - "titus-db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://titus:titus@titus-db:5432/titus
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

volumes:
  titus-pg-data:
    # run `docker volume create --name titus-pg-data -d local`
    external: true