apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "titus.db.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "titus.name" . }}
    helm.sh/chart: {{ include "titus.chart" . }}
    component: "{{ .Values.db.name }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.db.annotations | indent 4 }}
spec:
  schedule: "{{ .Values.db.schedule }}"
  {{- with .Values.db.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.db.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with .Values.db.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "titus.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: "{{ .Values.db.name }}"
    spec:
      activeDeadlineSeconds: 86400
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "titus.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            component: "{{ .Values.db.name }}"
          annotations:
{{ toYaml .Values.db.pod.annotations | indent 12 }}
        spec:
          restartPolicy: OnFailure
{{- if .Values.db.priorityClassName }}
          priorityClassName: "{{ .Values.db.priorityClassName }}"
{{- end }}
          containers:
            - name: {{ template "titus.name" . }}-{{ .Values.db.name }}
              image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
              imagePullPolicy: {{ .Values.db.image.pullPolicy }}
              ports:
                - containerPort: 5432
                  name: postgres
              resources:
{{ toYaml .Values.db.resources | indent 16 }}
    {{- with .Values.db.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.db.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.db.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}:
{{- end }}