apiVersion: v1
kind: Service
metadata:
  name: {{ include "titus.db.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "titus.name" . }}
    helm.sh/chart: {{ include "titus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: "{{ .Values.db.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "titus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: "{{ .Values.db.name }}"

