apiVersion: batch/v1
kind: Job
metadata:
  name: titus-db-migrate
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: titus-db-migrate
    spec:
      initContainers:
      - name: wait-for-db
        image: "actions/pg_isready"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "until pg_isready; do echo Waiting for postgres; sleep 2; done;"]
        env:
          - name: PGHOST
            value: {{ template "titus.database.host" . }}
          - name: PGPORT
            value: {{ template "titus.database.port" . }}
          - name: PGDATABASE
            value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          - name: PGUSER
            value: {{ .Values.postgresql.postgresqlUsername | quote }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "titus.database.secretName" . }}
                key: postgresql-password
      containers:
      - name: titus-db-migrate
        image: "titus-db-manager:latest"
        imagePullPolicy: IfNotPresent
        #command: ["until pg_isready -d $PG_DB -h $PG_HOST -p $PG_PORT -U $PG_USER; do echo Waiting for postgres; sleep 2; done;"]
        command: ["npm"]
        args: ["run", "db:migrate"]
        env:
          - name: NODE_ENV
            value: production
          - name: API_HOST
            value: {{ .Values.backend.apiHost | quote }}
          - name: API_PORT
            value: {{ .Values.backend.apiPort | quote }}
          - name: SECRETS_STRATEGY
            value: env
          - name: AUTH_PROVIDER
            value: {{ .Values.backend.authProvider | quote }}
          - name: PG_HOST
            value: {{ template "titus.database.host" . }}
          - name: PG_PORT
            value: {{ template "titus.database.port" . }}
          - name: PG_DB
            value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          - name: PG_USER
            value: {{ .Values.postgresql.postgresqlUsername | quote }}
          - name: SECRETS_PG_PASS
            value: PG_PASS
          - name: PG_PASS
            valueFrom:
              secretKeyRef:
                name: {{ template "titus.database.secretName" . }}
                key: postgresql-password
      restartPolicy: Never
