apiVersion: v1
kind: Service
metadata:
  name: '{{ include "..fullname" . }}-backend'
  labels:
    {{- include "..labels" . | nindent 4 }}
    tier: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
