apiVersion: v1
kind: Service
metadata:
  name: '{{ include "..fullname" . }}-frontend'
  labels:
    {{- include "..labels" . | nindent 4 }}
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
      {{ if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
