version: 0.2

env:
  shell: bash
  variables:
    HUSKY_SKIP_INSTALL: 1
    NODE_ENV: development
    DEPLOYER_ROLE_ARN: arn:aws:iam::YOURID_ACCOUNT:role/THE_ACCOUNT_CREATED_BY_THE_MIRA_CICD_COMMAND

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm run postinstall
  pre_build:
    commands:
#      - npm test test

  build:
    commands:
      - echo Deploy started on `date`
      - echo "Assuming role $DEPLOYER_ROLE_ARN ..."
      - CREDS=$(aws sts assume-role --role-arn $DEPLOYER_ROLE_ARN --role-session-name my-sls-session --out json)
      - echo $CREDS > temp_creds.json
      - export AWS_ACCESS_KEY_ID=$(node -p "require('./temp_creds.json').Credentials.AccessKeyId")
      - export AWS_SECRET_ACCESS_KEY=$(node -p "require('./temp_creds.json').Credentials.SecretAccessKey")
      - export AWS_SESSION_TOKEN=$(node -p "require('./temp_creds.json').Credentials.SessionToken")
      - aws sts get-caller-identity
      - npm run build:all
      - npm run deploy:ci -- --env=$ENVIRONMENT
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: '**/*'
