version: '3.6'

services:

  titus-db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      - POSTGRES_USER=titus
      - POSTGRES_PASSWORD=titus
      - POSTGRES_DB=titus
    ports:
      - "5432:5432"
    networks:
      - titus
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file: dev.env
    depends_on:
      - titus-db
    networks:
      - titus
    ports:
      - "5000:5000"
    volumes:
      - ..:/titus
    environment:
      - PGHOST=titus-db
      - PGPORT=5432

networks:
    titus:
