name: 'Backend CD to GCP'

on:
  push:
    branches:
      - master
      - feature/optimize-docker-images
    paths:
      - 'packages/titus-backend/**'
      - '.github/workflows/backend-cd-gcp.yml'
      - '.github/workflows/grype.yml'

env:
  DOCKER_SAVE_ARTIFACT: docker-save.tar

jobs:
  build-titus-backend:
    name: Build titus-backend
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      DOCKER_REGISTRY_HOST: europe-west1-docker.pkg.dev
      CLOUDRUN_SERVICE_NAME: titus-backend
      CLOUDRUN_SERVICE_REGION: europe-west1

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: latest
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker repository
        run: |
          gcloud components install beta
          gcloud beta auth configure-docker $DOCKER_REGISTRY_HOST

          echo "DOCKER_IMAGE=$DOCKER_REGISTRY_HOST/$PROJECT_ID/titus/backend:$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: ./packages/titus-backend
        run: docker build -t $DOCKER_IMAGE .

      - name: Export Docker image
        run: docker save $DOCKER_IMAGE > /tmp/$DOCKER_SAVE_ARTIFACT

      - name: Store Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.DOCKER_SAVE_ARTIFACT }}
          path: /tmp/${{ env.DOCKER_SAVE_ARTIFACT }}
          retention-days: 1

  docker-scan:
    needs: build-titus-backend
    uses: nearform/titus/.github/workflows/grype.yml@feature/optimize-docker-images
    with:
      docker-image: docker-save.tar
      scan-report: titus-backend

  deploy-titus-backend:
    name: Deploy titus-backend
    runs-on: ubuntu-latest
    needs: docker-scan

    steps:
      - name: Download Docker image from artifacts store
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.DOCKER_SAVE_ARTIFACT }}
          path: /tmp

      - name: Load frontend image
        run: |
          docker load --input /tmp/$DOCKER_SAVE_ARTIFACT
          docker image ls

      # - name: Push container
      #   working-directory: ./packages/titus-backend
      #   run: docker push $DOCKER_IMAGE

      # - name: Run service
      #   uses: google-github-actions/deploy-cloudrun@v0.7.0
      #   with:
      #     service: ${{ env.CLOUDRUN_SERVICE_NAME }}
      #     image: ${{ env.DOCKER_IMAGE }}
      #     credentials: ${{ secrets.GCP_SA_KEY }}
      #     region: ${{ env.CLOUDRUN_SERVICE_REGION }}
      #     project_id: ${{ env.PROJECT_ID }}

      - name: Delete Docker artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ env.DOCKER_SAVE_ARTIFACT }}   
