name: Backend CI
on:
  push:
    paths:
      - '.github/workflows/backend-ci.yml'
      - 'packages/titus-backend/**'
  pull_request:
    paths:
      - '.github/workflows/backend-ci.yml'
      - 'packages/titus-backend/**'

jobs:
  integration-checks:
    name: 'Linting, Testing'
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Installing dependencies
        working-directory: packages/titus-backend
        run: |
          npm ci

      - name: Running lint check
        working-directory: packages/titus-backend
        run: |
          npm run lint

      - name: Running tests
        working-directory: packages/titus-backend
        run: |
          npm run create:env
          npm run test

  automerge:
    needs: integration-checks
    runs-on: ubuntu-latest
    permissions:
     pull-requests: write
     contents: write    
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
