name: DB Manager CD to GCP

on:
  push:
    branches:
      - master
    paths:
      - 'packages/titus-db-manager/**'
      - '.github/workflows/db-manager-cd-gcp.yml'

jobs:
  deploy-titus-db-manager:
    name: Build & Deploy titus-db-manager
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      DOCKER_REGISTRY_HOST: europe-west1-docker.pkg.dev
      CLOUDRUN_SERVICE_NAME: titus-db-manager
      CLOUDRUN_SERVICE_REGION: europe-west1

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: latest
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker repository
        run: |
          gcloud components install beta
          gcloud beta auth configure-docker $DOCKER_REGISTRY_HOST

          echo "DOCKER_IMAGE=$DOCKER_REGISTRY_HOST/$PROJECT_ID/titus/db-manager:$GITHUB_SHA" >> $GITHUB_ENV

      - name: Install Grype tool (vulnerability scan)
        run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Build container
        working-directory: ./packages/titus-db-manager
        run: |
          docker build -t $DOCKER_IMAGE .

      - name: Scan image for vulnerabilities
        run: /usr/local/bin/grype $DOCKER_IMAGE | tee /tmp/vuln-scan-titus-db-manager.txt

      - name: Publish image scan results
        uses: actions/upload-artifact@v2
        with:
          name: vuln-scan-titus-db-manager.txt
          path: /tmp/vuln-scan-titus-db-manager.txt
          retention-days: 15

      - name: Push container
        working-directory: ./packages/titus-db-manager
        run: |
          docker push $DOCKER_IMAGE

      - name: Run service
        uses: google-github-actions/deploy-cloudrun@v0.7.0
        with:
          service: ${{ env.CLOUDRUN_SERVICE_NAME }}
          image: ${{ env.DOCKER_IMAGE }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: ${{ env.CLOUDRUN_SERVICE_REGION }}
          project_id: ${{ env.PROJECT_ID }}
