name: DB Manager CD to GCP

on:
  push:
    branches:
      - master
    paths:
      - 'packages/titus-db-manager/**'
      - '.github/workflows/deploy_titus_db_manager.yml'

jobs:
  deploy-titus-db-manager:
    name: Build & Deploy titus-db-manager
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      CLOUDRUN_SERVICE_NAME: titus-db-manager
      CLOUDRUN_SERVICE_REGION: europe-west1
      CI: true

    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Set up GCP CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker repository
        run: |
          echo "::set-env name=DOCKER_IMAGE::gcr.io/$PROJECT_ID/$CLOUDRUN_SERVICE_NAME:$GITHUB_SHA"
          gcloud auth configure-docker

      - name: Build container
        working-directory: ./packages/titus-db-manager
        run: |
          docker build -t $DOCKER_IMAGE .

      - name: Push container
        working-directory: ./packages/titus-db-manager
        run: |
          docker push $DOCKER_IMAGE

      - name: Run service
        working-directory: ./packages/titus-db-manager
        run: |
          gcloud run deploy $CLOUDRUN_SERVICE_NAME \
            --image $DOCKER_IMAGE \
            --region $CLOUDRUN_SERVICE_REGION \
            --project $PROJECT_ID \
            --platform managed
