name: Frontend CI
on:
  push:
    paths:
      - '.github/workflows/frontend-ci.yml'
      - 'packages/titus-frontend/**'
  pull_request:
    paths:
      - '.github/workflows/frontend-ci.yml'
      - 'packages/titus-frontend/**'

jobs:
  integration-checks:
    name: 'Linting, Testing, Building'
    runs-on: ubuntu-latest

    env:
      CI: true
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checking out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates fonts-liberation gconf-service libappindicator1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

      - name: Installing Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        working-directory: packages/titus-frontend
        run: |
          npm ci
          npm run create:env

      - name: Running lint check
        working-directory: packages/titus-frontend
        run: |
          npm run lint

      - name: Running tests
        working-directory: packages/titus-frontend
        run: |
          npm run test

      - name: Running build check
        working-directory: packages/titus-frontend
        run: |
          npm run build

      - name: Lighthouse check
        working-directory: packages/titus-frontend
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun \
            --upload.target=temporary-public-storage \
            --upload.githubAppToken=$LHCI_GITHUB_APP_TOKEN || echo "LHCI failed!"

      - name: Persist test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: image-snapshots
          path: packages/titus-frontend/src/__image_snapshots__/__diff_output__
