name: Docker image vulnerability scan with Grype

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      scan-report:
        required: true
        type: string

jobs:
  grype_scan:
    name: Grype scan
    runs-on: ubuntu-latest
    container:
      image: anchore/grype:latest

    steps:
      - name: Download Docker image from artifacts store
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.docker-image }}
          path: /tmp

      - name: Scan image for vulnerabilities
        run: /tmp/${{ inputs.docker-image }} | tee /tmp/vuln-scan-${{ inputs.scan-report }}.txt

      - name: Publish image scan results
        uses: actions/upload-artifact@v2
        with:
          name: vuln-scan-${{ inputs.scan-report }}.txt
          path: /tmp/vuln-scan-${{ inputs.scan-report }}.txt
          retention-days: 15
