name: Integration Checks
on: pull_request

jobs:
  integration-checks:
    name: 'Linting, Testing, Building'
    runs-on: ubuntu-latest
    
    env:
      CI: true

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checking out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget

      - name: Installing Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: |
          npm ci
          npm run create:env

      - name: Running lint check
        run: npm run lint:all

      - name: Running tests
        run: npm run test:all

      - name: Running build check
        run: npm run build:all
