name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checking out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Running build command
        run: |
          npm ci
          npm run create:env
          npm run build:all
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checking out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Running test command
        run: |
          npm ci
          npm run create:env
          npm run test:all
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checking out code
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Running test command
        run: |
          npm ci
          npm run create:env
          npm run lint:all
        env:
          CI: true
